// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';

import 'models/book.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 4387961578365705839),
      name: 'Book',
      lastPropertyId: const IdUid(4, 2914310562962358659),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 440511761705935766),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 5852570933097988751),
            name: 'title',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 6218204680826590668),
            name: 'author',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(1, 3535836821107933985),
            name: 'chapters',
            targetId: const IdUid(2, 7322332654755077441))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(2, 7322332654755077441),
      name: 'Chapter',
      lastPropertyId: const IdUid(1, 8984828347236359649),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 8984828347236359649),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(2, 4675358278237952481),
            name: 'paragraphs',
            targetId: const IdUid(3, 6493177431338303413))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(3, 6493177431338303413),
      name: 'Paragraph',
      lastPropertyId: const IdUid(1, 2415980714103244111),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 2415980714103244111),
            name: 'id',
            type: 6,
            flags: 1)
      ],
      relations: <ModelRelation>[
        ModelRelation(
            id: const IdUid(3, 2652675960758816000),
            name: 'pieces',
            targetId: const IdUid(4, 2797481375256060018))
      ],
      backlinks: <ModelBacklink>[]),
  ModelEntity(
      id: const IdUid(4, 2797481375256060018),
      name: 'Piece',
      lastPropertyId: const IdUid(3, 1415951895446300480),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 279090183780420962),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 3126761373932798512),
            name: 'content',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1415951895446300480),
            name: 'isWord',
            type: 1,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Store openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) =>
    Store(getObjectBoxModel(),
        directory: directory,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(4, 2797481375256060018),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(3, 2652675960758816000),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [2914310562962358659],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    Book: EntityDefinition<Book>(
        model: _entities[0],
        toOneRelations: (Book object) => [],
        toManyRelations: (Book object) =>
            {RelInfo<Book>.toMany(1, object.id): object.chapters},
        getId: (Book object) => object.id,
        setId: (Book object, int id) {
          object.id = id;
        },
        objectToFB: (Book object, fb.Builder fbb) {
          final titleOffset = fbb.writeString(object.title);
          final authorOffset = fbb.writeString(object.author);
          fbb.startTable(5);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, titleOffset);
          fbb.addOffset(2, authorOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Book(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              title: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              author: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''));
          InternalToManyAccess.setRelInfo(object.chapters, store,
              RelInfo<Book>.toMany(1, object.id), store.box<Book>());
          return object;
        }),
    Chapter: EntityDefinition<Chapter>(
        model: _entities[1],
        toOneRelations: (Chapter object) => [],
        toManyRelations: (Chapter object) =>
            {RelInfo<Chapter>.toMany(2, object.id): object.paragraphs},
        getId: (Chapter object) => object.id,
        setId: (Chapter object, int id) {
          object.id = id;
        },
        objectToFB: (Chapter object, fb.Builder fbb) {
          fbb.startTable(2);
          fbb.addInt64(0, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Chapter(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));
          InternalToManyAccess.setRelInfo(object.paragraphs, store,
              RelInfo<Chapter>.toMany(2, object.id), store.box<Chapter>());
          return object;
        }),
    Paragraph: EntityDefinition<Paragraph>(
        model: _entities[2],
        toOneRelations: (Paragraph object) => [],
        toManyRelations: (Paragraph object) =>
            {RelInfo<Paragraph>.toMany(3, object.id): object.pieces},
        getId: (Paragraph object) => object.id,
        setId: (Paragraph object, int id) {
          object.id = id;
        },
        objectToFB: (Paragraph object, fb.Builder fbb) {
          fbb.startTable(2);
          fbb.addInt64(0, object.id);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Paragraph(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0));
          InternalToManyAccess.setRelInfo(object.pieces, store,
              RelInfo<Paragraph>.toMany(3, object.id), store.box<Paragraph>());
          return object;
        }),
    Piece: EntityDefinition<Piece>(
        model: _entities[3],
        toOneRelations: (Piece object) => [],
        toManyRelations: (Piece object) => {},
        getId: (Piece object) => object.id,
        setId: (Piece object, int id) {
          object.id = id;
        },
        objectToFB: (Piece object, fb.Builder fbb) {
          final contentOffset = fbb.writeString(object.content);
          fbb.startTable(4);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, contentOffset);
          fbb.addBool(2, object.isWord);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = Piece(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              content: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              isWord: const fb.BoolReader()
                  .vTableGet(buffer, rootOffset, 8, false));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [Book] entity fields to define ObjectBox queries.
class Book_ {
  /// see [Book.id]
  static final id = QueryIntegerProperty<Book>(_entities[0].properties[0]);

  /// see [Book.title]
  static final title = QueryStringProperty<Book>(_entities[0].properties[1]);

  /// see [Book.author]
  static final author = QueryStringProperty<Book>(_entities[0].properties[2]);

  /// see [Book.chapters]
  static final chapters =
      QueryRelationToMany<Book, Chapter>(_entities[0].relations[0]);
}

/// [Chapter] entity fields to define ObjectBox queries.
class Chapter_ {
  /// see [Chapter.id]
  static final id = QueryIntegerProperty<Chapter>(_entities[1].properties[0]);

  /// see [Chapter.paragraphs]
  static final paragraphs =
      QueryRelationToMany<Chapter, Paragraph>(_entities[1].relations[0]);
}

/// [Paragraph] entity fields to define ObjectBox queries.
class Paragraph_ {
  /// see [Paragraph.id]
  static final id = QueryIntegerProperty<Paragraph>(_entities[2].properties[0]);

  /// see [Paragraph.pieces]
  static final pieces =
      QueryRelationToMany<Paragraph, Piece>(_entities[2].relations[0]);
}

/// [Piece] entity fields to define ObjectBox queries.
class Piece_ {
  /// see [Piece.id]
  static final id = QueryIntegerProperty<Piece>(_entities[3].properties[0]);

  /// see [Piece.content]
  static final content = QueryStringProperty<Piece>(_entities[3].properties[1]);

  /// see [Piece.isWord]
  static final isWord = QueryBooleanProperty<Piece>(_entities[3].properties[2]);
}
