name: Android Release

on:
  push:
    branches: [ "dev" ]
  pull_request:
    branches: [ "dev" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: "12.x"
          cache: 'gradle'
      - uses: subosito/flutter-action@v2
        with:
          channel: 'beta'
          cache: true
      - run: flutter --version
      - name: Get dependencies
        run: flutter pub get

      - name: Build the generated files
        run: flutter pub run build_runner build --delete-conflicting-outputs

      - name: Generate localization files
        run: flutter pub run easy_localization:generate -S "assets/translations"
      - run: flutter pub run easy_localization:generate -f keys -o locale_keys.g.dart -S "assets/translations"

      - name: Start release build
        run: flutter build appbundle
